app = 'ozencs-lab'
primary_region = 'waw'

[build]
  command = "pnpm install && pnpm run build"

[http_service]
  internal_port = 3000
  force_https = true
  auto_stop_machines = 'stop'
  auto_start_machines = true
  min_machines_running = 0
  processes = ['app']

[services]
concurrency = { hard_limit = 1, soft_limit = 1 }

[[vm]]
  memory = '256mb'
  cpu_kind = 'shared'
  cpus = 1
  memory_mb = 256

[env]
  NODE_ENV = "production"
  PORT = 3000
