import {
  HOMEPAGE_LOGO_DEFAULT_POSITION,
  HOMEPAGE_LOGO_DISABLED,
  HOMEPAGE_LOGO_MARKUP,
  HOMEPAGE_LOGO_POSITION_PLACEHOLDER,
  HOMEPAGE_LOGO_STYLE,
} from './html/homepage-logo';

export const HOMEPAGE_SLUG = 'hub';

export {
  HOMEPAGE_LOGO_DEFAULT_POSITION,
  HOMEPAGE_LOGO_DISABLED,
  HOMEPAGE_LOGO_MARKUP,
  HOMEPAGE_LOGO_POSITION_PLACEHOLDER,
  HOMEPAGE_LOGO_STYLE,
};
